#!/usr/bin/env bash
#
# Download the headline faces into web/src/fonts, and write the @font-face rules for them.
#
#   web/scripts/fetch-fonts.sh
#
# The woff2 files and fonts.css are committed, so nobody needs to run this to build the
# project — it exists so that "where did these binaries come from" has an answer that can be
# re-run, and so adding a face is an edit to the table below rather than an archaeology
# exercise.
#
# They are served from this instance and never from Google: rendering a front page must not
# make a reader's browser announce itself to a third party, which is the whole reason to
# self-host a font rather than link one.
#
# Four subsets each: latin and latin-ext between them cover every language written in the
# Latin alphabet, cyrillic and cyrillic-ext cover Russian and its neighbours.
#
# Nothing beyond those, and that is a decision rather than an omission. A script these faces
# cannot draw — Arabic, Greek, Han — falls back to the reading stack, which is what the page
# did before any of this existed, and every system already ships a face for it. Adding one
# is a line in the table below, at the price of the download.
#
# fonts.css is generated rather than written by hand for one specific reason: the
# unicode-range of each subset comes back from Google beside the URL it belongs to. Copying
# those ranges out by hand is how a font ends up downloaded for a page that has no glyph in
# it, or — worse — not downloaded for a page that does.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="$here/../src/fonts"
rm -rf "$out"
mkdir -p "$out"

# A browser User-Agent, and it is load-bearing: the css2 endpoint serves woff2 only to a
# client that looks like it can read woff2, and ttf to everything else.
UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

# slug|family|weight|ofl-directory|subsets — one line per face. A subset a family does not
# publish is skipped rather than fatal: Playfair Display has no cyrillic-ext, and there is
# nothing to be done about that here.
#
# The nameplate is not on this list because it needs nothing of its own — it is set in
# Playfair Display's 700, which is already here as a headline voice.
faces=(
  "playfair-display|Playfair Display|700|playfairdisplay|latin latin-ext cyrillic cyrillic-ext"
  "old-standard-tt|Old Standard TT|700|oldstandardtt|latin latin-ext cyrillic cyrillic-ext"
  "pt-serif|PT Serif|700|ptserif|latin latin-ext cyrillic cyrillic-ext"
  "bitter|Bitter|700|bitter|latin latin-ext cyrillic cyrillic-ext"
  "oswald|Oswald|600|oswald|latin latin-ext cyrillic cyrillic-ext"
  "alegreya|Alegreya|800|alegreya|latin latin-ext cyrillic cyrillic-ext"
)

css_out="$out/fonts.css"
license="$out/LICENSE.txt"

cat > "$css_out" <<'HEADER'
/*
 * The headline faces. Generated by ../../scripts/fetch-fonts.sh — edit the table there, not
 * this file.
 *
 * `swap` rather than `block` or `optional`, and the choice is between three ways of being
 * wrong for a moment. `block` hides text until the font lands, and on a page that is almost
 * entirely headlines that is a blank front page. `optional` never swaps, so the first visit
 * — the one where somebody decides what this thing looks like — gets none of the typography
 * the page is about. `swap` shows the reading face and then replaces it, which is a reflow
 * once, on a cold cache, before anybody has started reading. That is a load event rather
 * than the page reacting to being looked at, which is the rule it might otherwise break.
 */
HEADER

{
  echo "The faces in this directory are used under the SIL Open Font License, version 1.1."
  echo "Downloaded from Google Fonts by ../../scripts/fetch-fonts.sh, which is also where the"
  echo "list of them lives. The copyright notice for each follows; the licence itself, which"
  echo "is one and the same for all of them, is at the end."
  echo
} > "$license"

for face in "${faces[@]}"; do
  IFS='|' read -r slug family weight ofl subsets <<< "$face"
  css=$(curl -fsS -A "$UA" \
    "https://fonts.googleapis.com/css2?family=${family// /+}:wght@${weight}")

  got=""
  for subset in $subsets; do
    # The subset name is a comment above its @font-face block, so the URL and the range
    # wanted are the first of each after that comment. Matched exactly — "/* latin */" must
    # not be satisfied by the "/* latin-ext */" block that precedes it.
    read -r url range <<< "$(printf '%s' "$css" | awk -v want="/* $subset */" '
      $0 == want { hit = 1; next }
      hit && /src: url\(/ { match($0, /https:[^)]+/); url = substr($0, RSTART, RLENGTH) }
      hit && /unicode-range:/ {
        sub(/^[[:space:]]*unicode-range:[[:space:]]*/, ""); sub(/;[[:space:]]*$/, "")
        gsub(/,[[:space:]]*/, ","); print url, $0; exit
      }')"
    if [ -z "$url" ] || [ -z "$range" ]; then
      echo "  $family $weight: no $subset subset, skipped" >&2
      continue
    fi

    file="$slug-$weight-$subset.woff2"
    curl -fsS "$url" -o "$out/$file"
    got="$got $subset"

    {
      echo
      echo "/* $family $weight, $subset */"
      echo "@font-face {"
      echo "  font-family: \"$family\";"
      echo "  font-style: normal;"
      echo "  font-weight: $weight;"
      echo "  font-display: swap;"
      echo "  src: url(\"./$file\") format(\"woff2\");"
      echo "  unicode-range: ${range//,/, };"
      echo "}"
    } >> "$css_out"
  done

  # Every face must arrive with at least one subset. A family renamed upstream otherwise
  # leaves a voice with no files at all, and the page falls back to the reading face for it
  # — which looks like a design choice rather than a failed download.
  if [ -z "$got" ]; then
    echo "$family $weight: nothing downloaded" >&2
    exit 1
  fi
  printf '  %-22s %-4s %s\n' "$slug" "$weight" "$got"

  # The OFL requires the copyright notice to travel with the font. It is the first line of
  # each family's own licence file in google/fonts.
  {
    printf '%s — ' "$family"
    curl -fsS "https://raw.githubusercontent.com/google/fonts/main/ofl/$ofl/OFL.txt" \
      | grep -m1 -i '^Copyright'
  } >> "$license"
done

{
  echo
  echo "----------------------------------------------------------------------------------"
  echo
  curl -fsS "https://raw.githubusercontent.com/google/fonts/main/ofl/oswald/OFL.txt" \
    | sed -n '/^SIL OPEN FONT LICENSE/,$p'
} >> "$license"

echo "$(ls "$out"/*.woff2 | wc -l | tr -d ' ') faces, $(du -sh "$out" | cut -f1) total"
